-- =========================================================================
-- Batch INSERT all 30 Products into Supabase 'products' table
-- Paste and RUN this in Supabase SQL Editor if you prefer direct SQL import
-- =========================================================================

INSERT INTO products (
    id, name, description, brand, image, category, 
    retail_price, marketplace_price, stock_count, is_featured, 
    rating, reviews_count, specs, reviews, estimated_delivery, retailer_id
) VALUES
-- 1. Canada (CAD)
('p-amazon-200-cad', 'Amazon $200 Gift Card (CAD)', 'Send or redeem $200 on Amazon.ca with this Digital Amazon Gift Card. Delivered instantly to your email — no shipping, no waiting. Pay with Solana and receive your redeemable code the moment your transaction confirms.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 200, 200, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "Canada", "Currency": "CAD", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-150-cad', 'Amazon $150 Gift Card (CAD)', 'Send or redeem $150 on Amazon.ca with this Digital Amazon Gift Card. Delivered instantly to your email — no shipping, no waiting. Pay with Solana and receive your redeemable code the moment your transaction confirms.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 150, 150, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "Canada", "Currency": "CAD", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-100-cad', 'Amazon $100 Gift Card (CAD)', 'Send or redeem $100 on Amazon.ca with this Digital Amazon Gift Card. Delivered instantly to your email — no shipping, no waiting. Pay with Solana and receive your redeemable code the moment your transaction confirms.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 100, 100, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "Canada", "Currency": "CAD", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-75-cad', 'Amazon $75 Gift Card (CAD)', 'Send or redeem $75 on Amazon.ca with this Digital Amazon Gift Card. Delivered instantly to your email — no shipping, no waiting. Pay with Solana and receive your redeemable code the moment your transaction confirms.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 75, 75, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "Canada", "Currency": "CAD", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-50-cad', 'Amazon $50 Gift Card (CAD)', 'Send or redeem $50 on Amazon.ca with this Digital Amazon Gift Card. Delivered instantly to your email — no shipping, no waiting. Pay with Solana and receive your redeemable code the moment your transaction confirms.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 50, 50, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "Canada", "Currency": "CAD", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-25-cad', 'Amazon $25 Gift Card (CAD)', 'Send or redeem $25 on Amazon.ca with this Digital Amazon Gift Card. Delivered instantly to your email — no shipping, no waiting. Pay with Solana and receive your redeemable code the moment your transaction confirms.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 25, 25, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "Canada", "Currency": "CAD", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),

-- 2. Singapore (SGD)
('p-grab-100-sgd', 'GrabGift S$100 Voucher', 'Redeem S$100 for Grab Rides, GrabFood, GrabMart, and express deliveries in Singapore. Instant digital voucher code issued upon Solana settlement.', 'Grab', 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=500&auto=format&fit=crop', 'Food & Drink', 100, 100, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "Singapore", "Currency": "SGD", "Retailer Sourced": "grab"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-grab-80-sgd', 'GrabGift S$80 Voucher', 'Redeem S$80 for Grab Rides, GrabFood, GrabMart, and express deliveries in Singapore. Instant digital voucher code issued upon Solana settlement.', 'Grab', 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=500&auto=format&fit=crop', 'Food & Drink', 80, 80, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "Singapore", "Currency": "SGD", "Retailer Sourced": "grab"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-grab-50-sgd', 'GrabGift S$50 Voucher', 'Redeem S$50 for Grab Rides, GrabFood, GrabMart, and express deliveries in Singapore. Instant digital voucher code issued upon Solana settlement.', 'Grab', 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=500&auto=format&fit=crop', 'Food & Drink', 50, 50, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "Singapore", "Currency": "SGD", "Retailer Sourced": "grab"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-grab-30-sgd', 'GrabGift S$30 Voucher', 'Redeem S$30 for Grab Rides, GrabFood, GrabMart, and express deliveries in Singapore. Instant digital voucher code issued upon Solana settlement.', 'Grab', 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=500&auto=format&fit=crop', 'Food & Drink', 30, 30, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "Singapore", "Currency": "SGD", "Retailer Sourced": "grab"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-grab-20-sgd', 'GrabGift S$20 Voucher', 'Redeem S$20 for Grab Rides, GrabFood, GrabMart, and express deliveries in Singapore. Instant digital voucher code issued upon Solana settlement.', 'Grab', 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=500&auto=format&fit=crop', 'Food & Drink', 20, 20, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "Singapore", "Currency": "SGD", "Retailer Sourced": "grab"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-grab-10-sgd', 'GrabGift S$10 Voucher', 'Redeem S$10 for Grab Rides, GrabFood, GrabMart, and express deliveries in Singapore. Instant digital voucher code issued upon Solana settlement.', 'Grab', 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=500&auto=format&fit=crop', 'Food & Drink', 10, 10, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "Singapore", "Currency": "SGD", "Retailer Sourced": "grab"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),

-- 3. United Kingdom (GBP)
('p-amazon-150-gbp', 'Amazon £150 Gift Card (GBP)', 'Shop millions of items on Amazon.co.uk. Redeemable on UK Amazon accounts. Instant code delivery.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 150, 150, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United Kingdom", "Currency": "GBP", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-100-gbp', 'Amazon £100 Gift Card (GBP)', 'Shop millions of items on Amazon.co.uk. Redeemable on UK Amazon accounts. Instant code delivery.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 100, 100, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United Kingdom", "Currency": "GBP", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-75-gbp', 'Amazon £75 Gift Card (GBP)', 'Shop millions of items on Amazon.co.uk. Redeemable on UK Amazon accounts. Instant code delivery.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 75, 75, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United Kingdom", "Currency": "GBP", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-50-gbp', 'Amazon £50 Gift Card (GBP)', 'Shop millions of items on Amazon.co.uk. Redeemable on UK Amazon accounts. Instant code delivery.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 50, 50, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United Kingdom", "Currency": "GBP", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-30-gbp', 'Amazon £30 Gift Card (GBP)', 'Shop millions of items on Amazon.co.uk. Redeemable on UK Amazon accounts. Instant code delivery.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 30, 30, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United Kingdom", "Currency": "GBP", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-20-gbp', 'Amazon £20 Gift Card (GBP)', 'Shop millions of items on Amazon.co.uk. Redeemable on UK Amazon accounts. Instant code delivery.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 20, 20, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United Kingdom", "Currency": "GBP", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),

-- 4. United States (USD)
('p-amazon-200-usd', 'Amazon $200 Gift Card (USD)', 'Shop millions of products on Amazon.com. Valid for United States Amazon accounts. Instant digital code delivery.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 200, 200, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United States", "Currency": "USD", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-150-usd', 'Amazon $150 Gift Card (USD)', 'Shop millions of products on Amazon.com. Valid for United States Amazon accounts. Instant digital code delivery.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 150, 150, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United States", "Currency": "USD", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-100-usd', 'Amazon $100 Gift Card (USD)', 'Shop millions of products on Amazon.com. Valid for United States Amazon accounts. Instant digital code delivery.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 100, 100, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United States", "Currency": "USD", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-75-usd', 'Amazon $75 Gift Card (USD)', 'Shop millions of products on Amazon.com. Valid for United States Amazon accounts. Instant digital code delivery.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 75, 75, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United States", "Currency": "USD", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-50-usd', 'Amazon $50 Gift Card (USD)', 'Shop millions of products on Amazon.com. Valid for United States Amazon accounts. Instant digital code delivery.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 50, 50, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United States", "Currency": "USD", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-25-usd', 'Amazon $25 Gift Card (USD)', 'Shop millions of products on Amazon.com. Valid for United States Amazon accounts. Instant digital code delivery.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 25, 25, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United States", "Currency": "USD", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),

-- 5. United Arab Emirates (AED)
('p-amazon-200-aed', 'Amazon AED200 Gift Card', 'Shop millions of items on Amazon.ae in the United Arab Emirates. Instant digital gift card code.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 200, 200, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United Arab Emirates", "Currency": "AED", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-150-aed', 'Amazon AED150 Gift Card', 'Shop millions of items on Amazon.ae in the United Arab Emirates. Instant digital gift card code.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 150, 150, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United Arab Emirates", "Currency": "AED", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-100-aed', 'Amazon AED100 Gift Card', 'Shop millions of items on Amazon.ae in the United Arab Emirates. Instant digital gift card code.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 100, 100, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United Arab Emirates", "Currency": "AED", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-75-aed', 'Amazon AED75 Gift Card', 'Shop millions of items on Amazon.ae in the United Arab Emirates. Instant digital gift card code.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 75, 75, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United Arab Emirates", "Currency": "AED", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-50-aed', 'Amazon AED50 Gift Card', 'Shop millions of items on Amazon.ae in the United Arab Emirates. Instant digital gift card code.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 50, 50, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United Arab Emirates", "Currency": "AED", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon'),
('p-amazon-25-aed', 'Amazon AED25 Gift Card', 'Shop millions of items on Amazon.ae in the United Arab Emirates. Instant digital gift card code.', 'Amazon', 'https://m.media-amazon.com/images/I/31I63XNcY._AC_.jpg', 'Retail', 25, 25, 50, false, 5.0, 0, '{"Format": "Digital Code", "Region": "United Arab Emirates", "Currency": "AED", "Retailer Sourced": "amazon"}'::jsonb, '[]'::jsonb, 'Instant Digital Delivery', 'amazon')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    brand = EXCLUDED.brand,
    image = EXCLUDED.image,
    category = EXCLUDED.category,
    retail_price = EXCLUDED.retail_price,
    marketplace_price = EXCLUDED.marketplace_price,
    stock_count = EXCLUDED.stock_count,
    specs = EXCLUDED.specs;
